# Site settings
title: Chaosmail Blog
email: office(at)chaosmail.at
description: "Big Data and Artificial Intelligence Expert at Microsoft, Tech Author and Speaker"
baseurl: ""
url: "https://chaosmail.github.io/"
twitter_username: ChrisiKrnr
github_username:  chaosmail
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
 input: GFM

gems:
  - jekyll-paginate
